# Generated by Django 3.1.7 on 2021-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('race', models.CharField(default='Earthling', max_length=30)),
                ('height', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('mind', models.IntegerField(default=0)),
                ('recovery', models.IntegerField(default=0)),
                ('nature', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('movement', models.IntegerField(default=0)),
                ('sense', models.IntegerField(default=0)),
                ('solar', models.IntegerField(default=0)),
                ('path', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('power', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('sacrifice', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=40)),
                ('rage', models.CharField(max_length=40)),
                ('user', models.CharField(max_length=40)),
            ],
        ),
    ]
