# Generated by Django 3.1.7 on 2021-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='mind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default='Earthling', max_length=30),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
