# Generated by Django 3.1.7 on 2021-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210313_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='nature',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
